apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-controller-leader-writer
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller-leader-writer-binding
subjects:
- kind: ServiceAccount
  name: ingress-controller
  namespace: ingress-controller
roleRef:
  kind: ClusterRole
  name: ingress-controller-leader-writer
  apiGroup: rbac.authorization.k8s.io
