Vagrant.configure("2") do |config|

    # Master Nodes
    MasterCount = 1
    (1..MasterCount).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = "generic/ubuntu2004"
            master.vm.box_version = "3.6.8"
            master.vm.hostname = "master-#{i}"
            master.vm.network "private_network", ip: "172.16.1.1#{i}"

            master.vm.provider "virtualbox" do |vb|
                vb.name = "master-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    # Worker Nodes
    WorkerCount = 2
    (1..WorkerCount).each do |i|
        config.vm.define "k8s-worker-#{i}" do |worker|
            worker.vm.box = "generic/ubuntu2004"
            worker.vm.box_version = "3.6.8"
            worker.vm.hostname = "k8s-worker-#{i}"
            worker.vm.network "private_network", ip: "172.16.2.1#{i}"

            worker.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-worker-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
        end
    end

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            # Create root user
            useradd -s /bin/bash -d /root/ -m -G sudo root
            echo 'root ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            mkdir -p /root/.ssh && chown -R root /root/.ssh
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
    end
end
